services:
  postgres:
    image: postgres:latest
    container_name: ai-repo-postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 123456789
      POSTGRES_DB: ai_repo_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql

volumes:
  postgres_data: